
/*
 * 
 */

package com.ecity.skhg.rest;

import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Aug 02 09:23:12 CST 2013
 * Generated source version: 2.2.10
 * 
 */


@WebServiceClient(name = "NBPortAqServer", 
                  //wsdlLocation = "file:MapServer.wsdl",
                  targetNamespace = "http://www.esri.com/schemas/ArcGIS/10.0") 
public class SKHGServer extends Service {

    public final static URL WSDL_LOCATION;
    public final static QName SERVICE = new QName("http://www.esri.com/schemas/ArcGIS/10.0", "NBPortAqServer");
    public final static QName NBPortAqServerPort = new QName("http://www.esri.com/schemas/ArcGIS/10.0", "NBPortAqServerPort");
    static {
        URL url = null;
        //try {
        //    url = new URL("file:MapServer.wsdl");
        //} catch (MalformedURLException e) {
         //   System.err.println("Can not initialize the default wsdl from file:/E:/cd/CityServer-Java/src/Service-Plug/sp-MapServer/MapServer.wsdl");
         //   // e.printStackTrace();
        //}
        WSDL_LOCATION = url;
    }

    public SKHGServer(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public SKHGServer(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public SKHGServer() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     * 
     * @return
     *     returns MapServerPort
     */
    @WebEndpoint(name = "NBPortAqServerPort")
    public SKHGServerSoap getNBPortAqServerPort() {
        return super.getPort(NBPortAqServerPort, SKHGServerSoap.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns MapServerPort
     */
    @WebEndpoint(name = "NBPortAqServerPort")
    public SKHGServerSoap getNBPortAqServerPort(WebServiceFeature... features) {
        return super.getPort(NBPortAqServerPort, SKHGServerSoap.class, features);
    }

}
