package com.ecity.skhg.rest;

import javax.jws.WebService;

/**
 * This class was generated by Apache CXF 2.2.10
 * Fri Aug 02 09:23:12 CST 2013
 * Generated source version: 2.2.10
 * 
 */
 
@WebService(targetNamespace = "http://www.ecitychina.com/NBPortAqService/10.0", name = "NBPortAqService")
public interface SKHGLoaderServerSoap {
	
}
